- Dockerfile.openshift
We need to build the frr-metrics and add the frr-reloader for
the speakers to run frr.
This will fix the following CI error coming from the cp-reloader
container in the speaker pod:
`cp: can't stat '/frr-reloader.sh': No such file or directory`
> Add frr-metrics and frr-reloader to Openshift Dockerfile

- controller/controller_test.go
- controller/main.go
When edit configmap for existing service, the config was rejected and
not re-enqueued for reprocess when the service update takes place,
causing the service to stay in pending state till it get deleted
by k8s.
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
> Bug 2040394: Controller: enqueue the failed configmap till services update

- e2etest/bgptests/bgp.go
- e2etest/pkg/frr/bgp.go
- internal/bgp/frr/config.go
- internal/bgp/frr/testdata/TestSingleAdvertisement.golden
- internal/bgp/frr/testdata/TestTwoAdvertisements.golden
- internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
* FRR route-rules: add on-match next
When we have both communities and localpref advertisement, the
community advertisement is skipped because frr stops at the first match.
Here we add on-match next to let it continue.
Signed-off-by: Federico Paolinelli <fpaoline@redhat.com>
* E2E: refactor advertisement tests
We refactor the advertisement tests to reduce code duplication and to
have a way to test mixed scenarios where we have communities and
localpref in the same advertisement.
> Bug 2047238: FRR route-rules: add on-match next (#1201)

- speaker/bgp_controller.go
- speaker/layer2_controller.go
- speaker/layer2_controller_test.go
- speaker/main.go
> [release-4.9] Bug 2052549: L2: use externalips for speaker allocation

- e2etest/l2tests/l2.go
- speaker/main.go
The speaker metrics wasn't updated with deleted services because we were using the wrong label to delete it.
> Bug 2056967: Speaker metrics: Bug fix: wrong label 

- openshift-ci/README.md
- openshift-ci/common.sh
- openshift-ci/deploy_metallb.sh
- openshift-ci/metallb-operator-deploy/controller_manager_patch.yaml
- openshift-ci/metallb-operator-deploy/kustomization.yaml
- openshift-ci/run_e2e.sh
Moving the logic from dev-scripts repo here allows us easy update when needed. In addition, every change done in the
scripts will be tested by OCP CI.
So far, every change we made in MetalLB dev-scripts wasn't tested since the CI in dev-scripts repo is not configured
to test MetalLB (this shouldn't be changed since dev-scripts are used by many CI lanes and MetalLB shouldn't affect them).
> Move CI config files from dev-scripts repo

- openshift-ci/run_e2e.sh
The path of the kubeconfig file doesn't match the location in OCP CI clusters.
> openshift-ci: Fix kubeconfig path

- controller/controller_test.go
- controller/service.go
- internal/allocator/allocator.go
Users prefer seeing errors when modify services that are sharing the sameIP
using "allow-shared-ip" annotation than getting newly allocated serviceIP
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
> Bug 2055386: When services share IP, modifying any service should fail instead of allocating newIP

- openshift-ci/README.md
- openshift-ci/common.sh
- openshift-ci/deploy_metallb.sh
- openshift-ci/metallb-operator-deploy/controller_manager_patch.yaml
- openshift-ci/metallb-operator-deploy/kustomization.yaml
- openshift-ci/run_e2e.sh
Moving the logic from dev-scripts repo here allows us easy update when needed. In addition, every change done in the
scripts will be tested by OCP CI.
So far, every change we made in MetalLB dev-scripts wasn't tested since the CI in dev-scripts repo is not configured
to test MetalLB (this shouldn't be changed since dev-scripts are used by many CI lanes and MetalLB shouldn't affect them).
> Bug 2059945: Move CI config files from dev-scripts repo

- openshift-ci/metallb-operator-deploy/kustomization.yaml
Due to the recent changes in metallb-operator (moving the webhooks to metallb) the deployment path should be updated.
> openshift-ci: change kustomize path

- .github/dependabot.yml
This reverts commit 22bcca095fee736aca9d63aab2dd0220b8c8d70d.
We track of the dependencies upstream, and d/s only reflects them.
Dependabot just creates noise.
> Revert "Add dependabot file to track go deps"

- openshift-ci/run_e2e.sh
The path of the file was not accurate, metallb_dir refers to
metallb/openshift_ci. We need to raise a level.
To cut me some slack, I did not see the error in the previous CI run because it was finishing before patching the file.
Temporarily removing the `-e` flag to see if patching finally works or not.
> Bug 2089827: Refix backward compatibility patch

- internal/k8s/k8s.go
Controller-runtime is starting a metrics endpoint on port 8080 by default, and prevents the speaker from starting if the port
is in use. Disabling the metrics endpoint in controller-runtime for the time, we might want to enable these metrics in the future.
> Bug 2099875: Disable metrics endpoint in controller-runtime

- e2etest/bgptests/bgp.go
- e2etest/bgptests/bgp_multiprotocol.go
- e2etest/pkg/frr/config/config.go
- e2etest/pkg/frr/container/container.go
- e2etest/pkg/frr/validation.go
- e2etest/pkg/service/tweak.go
- internal/bgp/frr/config.go
- internal/bgp/frr/frr.go
- internal/bgp/frr/parse.go
- internal/bgp/frr/testdata/TestBFDWithSession.golden
- internal/bgp/frr/testdata/TestSingleAdvertisement.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementNonExistingPeer.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementWithPeerSelector.golden
- internal/bgp/frr/testdata/TestSingleEBGPSessionMultiHop.golden
- internal/bgp/frr/testdata/TestSingleEBGPSessionOneHop.golden
- internal/bgp/frr/testdata/TestSingleIBGPSession.golden
- internal/bgp/frr/testdata/TestSingleIPv6EBGPSessionOneHop.golden
- internal/bgp/frr/testdata/TestSingleIPv6IBGPSession.golden
- internal/bgp/frr/testdata/TestTwoAdvertisements.golden
- internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
- internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessionsOneWithPeerSelector.golden
- internal/bgp/frr/testdata/TestTwoIPv6Sessions.golden
- internal/bgp/frr/testdata/TestTwoSessions.golden
- internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden
- internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
Found by an upstream user, we broke MP bgp support between 4.10 and 4.11, this is restoring it.
> Bug 2100035: Fix MP BGP

- internal/bgp/frr/config.go
- internal/bgp/frr/debounce_test.go
- internal/bgp/frr/frr.go
- internal/bgp/frr/frr_test.go
Making the interaction with FRR more robust introducing retries after failures in both the call of the reloader (if the pid is not there yet) and if we find that the interaction between the reloader and the container fails.
> Bug 2102673: fix frr start race condition

- api/v1beta1/l2advertisement_webhook.go
- api/v1beta1/l2advertisement_webhook_test.go
- api/v1beta1/mock_validator_test.go
- charts/metallb/templates/webhooks.yaml
- config/manifests/metallb-frr.yaml
- config/manifests/metallb-native.yaml
- config/webhook/manifests.yaml
- internal/k8s/k8s.go
The validation webook is currently missing for l2 adv
object, this commit ensures such validating webhook
implmented for it.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit 240aed9d70f5156c13261a29265a6b1e170a9ab8)
> Bug 2100845: Add validation webhook for L2Advertisement

- e2etest/bgptests/bgp.go
- e2etest/l2tests/l2.go
- e2etest/pkg/metrics/metrics.go
- internal/k8s/controllers/config_controller.go
- internal/k8s/controllers/node_controller.go
- internal/k8s/controllers/pool_controller.go
- internal/k8s/controllers/service_controller.go
- internal/k8s/controllers/stats.go
In migrating to CRDs, we omitted filling the metrics related to k8s events. Here we re introduce them.
> Bug 2102676: restore k8s events metrics

- internal/layer2/announcer.go
This reverts commit 9936f3b89a96e6e05bbddae815b6351d4ee243c1.
There's a use case where metallb is used together with vlan interfaces
with no ips which wouldn't work with this change.
For this reason, it makes sense to listen and announce on interfaces
with no ip.
> Bug 2109059: Revert "Filter out no IP interfaces for L2 advertisement"

- openshift-ci/deploy_metallb.sh
We were not increasing the number of iterations, causing an infinite loop.
Also allow running build index container on restricted environments, to fix the following error from build index container:
Error from server (Forbidden): error when creating "STDIN": pods "buildindex" is forbidden: violates PodSecurity "restricted:v1.24": privileged (container "priv" must not set securityContext.privileged=true), allowPrivilegeEscalation != false (container "priv" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "priv" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "priv" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "priv" must set securityContext.seccompProfile.type to …
> openshift-ci: Fix wait for build index container loop

- charts/metallb/README.md
- charts/metallb/policy/speaker.rego
- charts/metallb/templates/speaker.yaml
- charts/metallb/values.schema.json
- charts/metallb/values.yaml
- config/controllers/speaker.yaml
- config/manifests/metallb-frr-prometheus.yaml
- config/manifests/metallb-frr.yaml
- config/manifests/metallb-native-prometheus.yaml
- config/manifests/metallb-native.yaml
- internal/k8s/k8s.go
- speaker/main.go
This PR cherry-picks the commits in upstream MetalLB, 
changing the speaker's memberlist secret from env var to mounted file,
from security concerns.
> OCPBUGS-2777: read memberlist secret from file instead of env var 

- frr-reloader/frr-reloader.sh
- internal/k8s/controllers/config_controller.go
- internal/k8s/controllers/dump.go
- internal/k8s/controllers/pool_controller.go
Downstream port of hiding bgp passwords from the logs of the reloader and from the speaker pods with debug loglevel
> OCPBUGS-3825: hide the bgp password from the logs

- internal/k8s/controllers/config_controller.go
- internal/k8s/controllers/config_controller_test.go
- internal/k8s/controllers/node_controller.go
- internal/k8s/controllers/node_controller_test.go
Backporting two changes here, where we check if the nodes in the node reconciler did not change and if the applied configuration is producing any changes worth the reload.
> OCPBUGS-7082: skip unnecessary events

- charts/metallb/README.md
- charts/metallb/policy/speaker.rego
- charts/metallb/templates/speaker.yaml
- charts/metallb/values.schema.json
- charts/metallb/values.yaml
- config/controllers/speaker.yaml
- config/manifests/metallb-frr-prometheus.yaml
- config/manifests/metallb-frr.yaml
- config/manifests/metallb-native-prometheus.yaml
- config/manifests/metallb-native.yaml
- speaker/main.go
This PR backports the fix for OCPBUGS-2777 from upstream.
This makes the speaker read the memberlist secret from a file and not from env var.
> OCPBUGS-8019: Read the memberlist secret from a file

- controller/service.go
- internal/config/config.go
- internal/config/config_test.go
Manual cherry-pick of 22f152b7816ef0ecaf6ec749b9571a4e236ff454 and 630ffa8d0a7eb8a11c64763412a18f7bc791f8c8, no conflicts.
> OCPBUGS-10697,OCPBUGS-10698: ippool service allocation fixes

- charts/metallb/README.md
- charts/metallb/policy/speaker.rego
- charts/metallb/templates/speaker.yaml
- charts/metallb/values.schema.json
- charts/metallb/values.yaml
- config/controllers/speaker.yaml
- config/manifests/metallb-frr.yaml
- config/manifests/metallb-native.yaml
- internal/k8s/k8s.go
- speaker/main.go
This is a cherry-pick from 4.12.
https://github.com/openshift/metallb/pull/107
Makes the memberlist secret env var hold the path to the secret instead the secret itself.
and makes the speaker consume the secret by reading from that path.
> OCPBUGS-14277: 4.11 backport: read memberlist secret from file instead of env var

- charts/metallb/README.md
- charts/metallb/policy/speaker.rego
- charts/metallb/templates/speaker.yaml
- charts/metallb/values.schema.json
- charts/metallb/values.yaml
- internal/k8s/k8s.go
- manifests/metallb-frr.yaml
- manifests/metallb.yaml
- speaker/main.go
This is a cherry-pick from 4.11 
#124 
Makes the memberlist secret env var hold the path to the secret instead the secret itself.
and makes the speaker consume the secret by reading from that path.
> OCPBUGS-14503: [4.10]  read memberlist secret from file instead of env var

- internal/bgp/frr/config.go
- internal/bgp/frr/frr_test.go
- internal/bgp/frr/templates/filters.tmpl
- internal/bgp/frr/testdata/TestBFDWithSession.golden
- internal/bgp/frr/testdata/TestSingleAdvertisement.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementChange.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementNoRouterID.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementNonExistingPeer.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementStop.golden
- internal/bgp/frr/testdata/TestSingleAdvertisementWithPeerSelector.golden
- internal/bgp/frr/testdata/TestSingleEBGPSessionMultiHop.golden
- internal/bgp/frr/testdata/TestSingleEBGPSessionOneHop.golden
- internal/bgp/frr/testdata/TestSingleIBGPSession.golden
- internal/bgp/frr/testdata/TestSingleIPv6EBGPSessionOneHop.golden
- internal/bgp/frr/testdata/TestSingleIPv6IBGPSession.golden
- internal/bgp/frr/testdata/TestSingleSessionExtras.golden
- internal/bgp/frr/testdata/TestTwoAdvertisements.golden
- internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessions.golden
- internal/bgp/frr/testdata/TestTwoAdvertisementsTwoSessionsOneWithPeerSelector.golden
- internal/bgp/frr/testdata/TestTwoIPv6Sessions.golden
- internal/bgp/frr/testdata/TestTwoSessions.golden
- internal/bgp/frr/testdata/TestTwoSessionsDuplicate.golden
- internal/bgp/frr/testdata/TestTwoSessionsDuplicateRouter.golden
Instead of letting frr pick the sequence number, we provide it from outside. This should make the configuration more deterministic and offload some of the logic from FRR.
> OCPBUGS-19053: FRR templates: provide a seqnum for the prefix lists

- e2etest/bgptests/bgp.go
- e2etest/bgptests/validate.go
- e2etest/l2tests/assignment.go
- e2etest/pkg/k8s/pods.go
- e2etest/pkg/metallb/metallb.go
- e2etest/pkg/service/validate.go
- internal/k8s/controllers/service_controller.go
- internal/k8s/controllers/service_controller_reload.go
- internal/k8s/controllers/service_controller_test.go
- internal/k8s/nodes/nodes.go
This PR changes the behavior of the service reconciler
to fix the following bug:
- There is an LB service with a specific IP (annotated) assigned to it.
- Also there are other LB services in the cluster on "pending".
- MetalLB's controller resets and when it goes back up again,
it loops over the services, sees first the "pending" LB service,
and assigns it the IP that was assigned to the annotated service.
Here we make the reconciler ignore the services, up until the first
reprocessAll event, where we handle only the services with IP assigned
to them already.
> OCPBUGS-19745: Preserve internal state after reboot

- e2etest/bgptests/bgp.go
- e2etest/bgptests/validate.go
- e2etest/l2tests/assignment.go
- e2etest/pkg/k8s/pods.go
- e2etest/pkg/metallb/metallb.go
- e2etest/pkg/service/validate.go
- internal/k8s/controllers/service_controller.go
- internal/k8s/controllers/service_controller_reload.go
- internal/k8s/controllers/service_controller_test.go
- internal/k8s/nodes/nodes.go
This PR changes the behavior of the service reconciler
to fix the following bug:
There is an LB service with a specific IP (annotated) assigned to it.
Also there are other LB services in the cluster on "pending".
-MetalLB's controller resets and when it goes back up again,
it loops over the services, sees first the "pending" LB service,
and assigns it the IP that was assigned to the annotated service.
Here we make the reconciler ignore the services, up until the first
reprocessAll event, where we handle only the services with IP assigned
to them already.
> [release 4.14] OCPBUGS-16267: Fix controller reboot bug

- e2etest/bgptests/bgp.go
- e2etest/bgptests/validate.go
- e2etest/l2tests/assignment.go
- e2etest/pkg/k8s/pods.go
- e2etest/pkg/metallb/metallb.go
- e2etest/pkg/service/create.go
- e2etest/pkg/service/validate.go
- internal/k8s/controllers/service_controller.go
- internal/k8s/controllers/service_controller_reload.go
- internal/k8s/controllers/service_controller_test.go
This PR changes the behavior of the service reconciler
to fix the following bug:
There is an LB service with a specific IP (annotated) assigned to it.
Also there are other LB services in the cluster on "pending".
-MetalLB's controller resets and when it goes back up again,
it loops over the services, sees first the "pending" LB service,
and assigns it the IP that was assigned to the annotated service.
Here we make the reconciler ignore the services, up until the first
reprocessAll event, where we handle only the services with IP assigned
to them already.
> OCPBUGS-23425: Fix controller reboot bug 4.12

- .snyk
Skipping:
- the vendor folder
- any test file
- all the e2etest files
> OCPBUGS-25266: Add a .snyk file with the files to skip

- internal/bgp/frr/frr.go
- internal/bgp/frr/frr_test.go
- internal/bgp/frr/testdata/TestTwoAdvertisementsDuplicate.golden
Passing multiple advertisements with the same prefix to the template causes duplicate entries. This happens for example when the shared ip annotation is used with the services.
Since a given advertisement has the related peers as fields, the right place to squash is when we manage the advertisements related to a given neighbor.
> [release-4.13] OCPBUGS-33759: FRR: squash advertisements with the same prefix

- internal/bgp/frr/frr.go
- internal/bgp/frr/frr_test.go
- internal/bgp/frr/testdata/TestTwoAdvertisementsDuplicate.golden
Passing multiple advertisements with the same prefix to the template
causes duplicate entries. This happens for example when the shared ip
annotation is used with the services.
Since a given advertisement has the related peers as fields, the right
place to squash is when we manage the advertisements related to a given
neighbor.
non clean backport of https://github.com/openshift/metallb/pull/174
> OCPBUGS-33936: FRR: squash advertisements with the same prefix

- openshift-ci/deploy_metallb.sh
We are moving the default to frr-k8s, so for the time being we set explicitly the backend to frr in case of frr jobs, otherwise we might incur in the scenario where the tests think it's frr while the deployment is frr-k8s based.
Needed to fix the failures in https://github.com/openshift/metallb-operator/pull/231
> CI: explicitly set frr when running with frr as backend

- openshift-ci/metallb-operator-deploy/build_and_push_index.sh
because openshift-ci is failing with hidden error
```
Error: logging into "image-registry.openshift-image-registry.svc:5000": invalid username/password
```
and buildindeximage pod to status ImagePullBackOff
> OCPBUGS-35864: ci: fix registry auth error

- openshift-ci/deploy_metallb.sh
From 4.17, the kuberbac proxy is not available on quay anymore. Here we treat is as with the other operands, replacing it with what's available on the CI registry.
> Openshift CI: override the kuberbac proxy image too

- openshift-ci/deploy_metallb.sh
Now that it's the default we can unset it.
> OpenshiftCI: unset the frr-k8s backend on the frr-k8s lane

- openshift-ci/deploy_metallb.sh
- openshift-ci/metallb-operator-deploy/frrk8s-cno.patch
- openshift-ci/run_e2e.sh
While keeping both deployment methods, we allow to enable the feature gate and tell the metallb operator to interact with CNO to deploy frr-k8s.
> Openshift CI: enable a lane to deploy frr-k8s via CNO

- e2etest/bgptests/bgp.go
- e2etest/pkg/frr/bgp.go
- e2etest/pkg/frr/parse.go
- e2etest/pkg/frr/parse_test.go
- e2etest/pkg/frr/validation.go
- internal/bgp/frr/templates/neighborsession.tmpl
- internal/bgp/frr/testdata/TestBFDWithSession.golden
Backporting the fix and the tests
> OCPBUGS-37294: backport bfd flaps when updating a service

- e2etest/bgptests/bgp.go
- e2etest/pkg/frr/bgp.go
- e2etest/pkg/frr/parse.go
- e2etest/pkg/frr/validation.go
- internal/bgp/frr/templates/neighborsession.tmpl
- internal/bgp/frr/testdata/TestBFDWithSession.golden
Backporting the fix and the tests
> OCPBUGS-37295: Sessions flapping when a service is added, backporting

- openshift-ci/deploy_metallb.sh
- openshift-ci/run_e2e.sh
- Wait for metallb pods to appear
- Wait for the proper endpoints behind the metallb validation service
- Pass the FRR-K8s namespace when running externally
> FRR-K8S via CNO fixes

- e2etest/pkg/frr/container/container.go
Trying to fix the
"Error: short-name resolution enforced but cannot prompt without a TTY" we are getting in CI.
> OCPBUGS-25783: D/S only: fix the frr path used by tests

- openshift-ci/deploy_metallb.sh
- openshift-ci/enable_frrk8s_on_cno.sh
- openshift-ci/run_e2e.sh
- openshift-ci/run_frrk8s_e2e.sh
- openshift-ci/run_metallb_e2e.sh
Running frrk8s e2e tests to make sure we don't regress.
Note: despite the fact that this PR won't execute the frr tests in the latest version, it was tested by forcing the execution of the tests here https://github.com/openshift/metallb/pull/198/files#diff-e2ff966b1775ad5e6d156754f37e1ae53615a0dfb1ecdd123728f70a1235ae2aR32
Once this merges, new lanes will be defined under frr
> Openshift CI: run frr-k8s e2e tests

- e2etest/l2tests/l2.go
- e2etest/pkg/config/validate.go
- internal/allocator/allocator.go
- internal/allocator/allocator_test.go
- internal/allocator/stats.go
- website/content/release-notes/_index.md
Backporting the per ip family allocation metrics
> OCPBUGS-44730: Metrics: add ipv4/6 addresses_in_use_total and addresses_total

- openshift-ci/deploy_metallb.sh
- openshift-ci/frrk8sdebug_cm.yaml
- openshift-ci/patchcvo_overridefrrk8s.yaml
- openshift-ci/run_metallb_e2e.sh
We are enabling it by default, so there is no point in setting the env variables.
Also, moving the frr-k8s job to work as frr-k8s-cno as it's going to be the only operating mode (and we want to see CI passing). Next step is going to be removing one of the two jobs as now they are identical.
> frr-k8s via cno job: don't change the csv

- internal/bgp/frrk8s/frrk8s.go
- internal/bgp/frrk8s/frrk8s_test.go
- internal/bgp/frrk8s/testdata/TestTwoAdvertisementsWithSamePrefix.golden
> OCPBUGS-46554: frr-k8s: Make sure no duplicates prefix are passed to backend

- openshift-ci/run_frrk8s_e2e.sh
skipping unnumbered tests since we don't have a setup for it in dev-scripts
> OpenShift only: skip Unnumbered e2es

- internal/k8s/epslices/endpoint_slices.go
- internal/k8s/epslices/endpoint_slices_test.go
- speaker/bgp_controller.go
- speaker/bgp_controller_test.go
- speaker/layer2_controller.go
- speaker/layer2_controller_test.go
instead of looking at the serving condition first, we look at the ready condition which has precendence. This allows metallb to respect the publishNotReadyAddresses field of the services.
> OCPBUGS-51175: Fix the handling of readyness conditions of endpointslices

- openshift-ci/run_frrk8s_e2e.sh
Since we don't run any VRF containers the test doesn't make sense, and it panics because it tries to access an element from the empty containers slice:
```
BGPSessionState BGP and BFD Each node manages its statuses [It] IPV4 - VRF
/root/dev-scripts/frr/e2etests/tests/bgp_session_status.go:348
[PANICKED] Test Panicked
In [It] at: /root/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.11.linux-amd64/src/runtime/panic.go:114 @ 04/04/25 05:28:19.433
runtime error: index out of range [0] with length 0
```
> OpenShift only: skip BGPSessionState VRF test

- openshift-ci/run_frrk8s_e2e.sh
Missed "\", failing with:
```
bash: line 1: BGPSessionState.*VRF|IPV6|DUALSTACK: command not found
```
> OpenShift only: fix the skip of BGPSessionState VRF test

- openshift-ci/run_frrk8s_e2e.sh
The tests aren't compatible with d/s because the poll-interval for the status sidecar container is too large. We'll skip these tests for now and add a smoke test for the feature.
> OpenShift only: skip existing BGPSessionState e2es

- .gitignore
- vendor/github.com/onsi/ginkgo/v2/ginkgo/build/build_command.go
```
git cherry-pick 31643ca
[release-419-ocp56733 22969d4dc] Ignore top level build folder only
Date: Thu May 8 10:18:41 2025 +0200
1 file changed, 1 insertion(+), 1 deletion(-)
go mod vendor
[I] ~/w/g/m/w/metallb-downstream (release-419-ocp56733 ↑1 ✔) ❯ git status
On branch release-419-ocp56733
Your branch is ahead of 'openshift/release-4.19' by 1 commit.
(use "git push" to publish your local commits)
Untracked files:
(use "git add <file>..." to include in what will be committed)
vendor/github.com/onsi/ginkgo/v2/ginkgo/build/
```
> OCPBUGS-56733: cherry-pick commit to ignore only  top level build folder

- openshift-ci/common.sh
- openshift-ci/deploy_frr_k8s_from_cno.sh
- openshift-ci/deploy_metallb.sh
Enabling debug logs as we might need them when triaging CI failures.
> Openshift CI: enable frrk8s debug logs
