Dockerfile.openshift
To match the u/s images where the entrypoints are /controller and /speaker
=> Update controller and speaker image entrypoint

OWNERS
This to add myself to the approvers.
=> Add Federico to the approvers

controller/controller_test.go, controller/main.go, internal/k8s/k8s.go, speaker/main.go
This PR cherry pick u/s [PR #1028](https://github.com/metallb/metallb/pull/1028) and [PR #1166](https://github.com/metallb/metallb/pull/1166)
=> Bug 2039507: fix updates to deployed addresspool and svc in any order

controller/main.go, e2etest/pkg/frr/config/config.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_bfd_test.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestLoggingConfiguration.golden, internal/bgp/frr/testdata/TestLoggingConfigurationDebug.golden, internal/bgp/frr/testdata/TestLoggingConfigurationOverrideByEnvironmentVar.golden, internal/logging/logging.go, manifests/example-config.yaml, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/main.go, website/content/_index.md, website/content/community/_index.md, website/content/concepts/bgp.md, website/content/configuration/_index.md, website/content/installation/_index.md, website/content/release-notes/_index.md, website/content/usage/_index.md
Propagate speaker's --log-level parameter to the FRR containers.
=> Bug 2060037: Forward speaker log level to FRR configuration

openshift-ci/run_e2e.sh
Adding this to validate the conversion webhooks work and if metallb is compatible with the CRDs in the operator.
=> openshift CI: Add backward compatibility testing

openshift-ci/deploy_metallb.sh, openshift-ci/run_e2e.sh
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
=> Bug 2088535: change log level to debug for openshift ci

internal/config/config.go, internal/config/config_test.go
This commit validates duplicate values in ip address pool, ip address
pool selector, node selector and peers fields and throw an error
when such duplicates are found.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit fdefacd04eb02ab692a970f870f5d31687e7b1f3)
=> Bug 2090755: Add validation for BGP and L2 advertisement

internal/config/config.go, internal/config/config_test.go
This validates duplicate values specified in node, ip pool
selectors match expressions under bgp peer, bgp and l2
advertisements.
Signed-off-by: Periyasamy Palanisamy <pepalani@redhat.com>
(cherry picked from commit f157d55e43d779a50ac66460370b761ce6f1f1a8)
=> Bug 2097047: Validate crd match expressions

internal/layer2/announcer.go, internal/layer2/ip_advertisement.go
Downstream port of the fix for https://github.com/metallb/metallb/issues/1727
=> OCPBUGS-4245: l2 more robust in case metallb can't listen to arp requests

charts/metallb/templates/rbac.yaml, config/manifests/metallb-frr-prometheus.yaml, config/manifests/metallb-frr.yaml, config/manifests/metallb-native-prometheus.yaml, config/manifests/metallb-native.yaml, config/rbac/role.yaml, e2etest/bgptests/infra_setup.go, e2etest/l2tests/assignment.go, go.mod, internal/bgp/frr/frr.go, internal/bgp/frr/frr_vrf_test.go, internal/bgp/frr/testdata/TestTwoSessionsSameIPRouterIDASNVRF.golden, internal/config/validation.go, internal/config/validation_test.go, vendor/modules.txt, website/content/configuration/_advanced_bgp_configuration.md
=> Align with upstream 010223

.github/workflows/ci.yaml, .github/workflows/publish.yaml, .github/workflows/vulncheck.yaml, .github/workflows/vulncheck_periodic.yaml, charts/metallb/README.md, charts/metallb/templates/controller.yaml, charts/metallb/values.yaml, configsamples/bgppeer_with_vrf.yaml, configsamples/ipaddresspool_with_selector.yaml, controller/controller_test.go, controller/main.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, website/content/configuration/_advanced_bgp_configuration.md, website/content/configuration/_advanced_ipaddresspool_configuration.md, website/content/release-notes/_index.md, website/content/usage/_index.md
=> Align with upstream 200223

controller/main.go, e2etest/pkg/frr/config/config.go, internal/bgp/frr/config.go, internal/bgp/frr/frr.go, internal/bgp/frr/frr_bfd_test.go, internal/bgp/frr/frr_test.go, internal/bgp/frr/testdata/TestLoggingConfiguration.golden, internal/bgp/frr/testdata/TestLoggingConfigurationDebug.golden, internal/bgp/frr/testdata/TestLoggingConfigurationOverrideByEnvironmentVar.golden, internal/logging/logging.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/main.go, website/content/installation/_index.md
This PR backports the metallb log level feature, from the following PRs:
https://github.com/metallb/metallb/pull/1198
https://github.com/metallb/metallb/pull/1180
PRs was written by Andrea Panattoni <apanatto@redhat.com>
=> OCPBUGS-11861: Backport MetalLB log level feature

e2etest/bgptests/bgp.go, e2etest/bgptests/infra_setup.go, e2etest/bgptests/validate.go, e2etest/e2etest_suite_test.go, e2etest/l2tests/assignment.go, e2etest/pkg/frr/config/config.go, e2etest/pkg/frr/container/container.go, openshift-ci/run_e2e.sh, tasks.py
- use 8.3.1 for the external frr instance to match the version and allow echo to work on ibgp
- retry when labeling the namespace for allocation tests
- add an extra injection test
=> OCPBUGS-14362: Fix the failing tests

internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/config_conversion.go, internal/k8s/controllers/config_conversion_test.go, internal/k8s/controllers/pool_controller.go
If the produced configuration does not change, we should not reload the frr configuration.
=> OCPBUGS-15415: don't reload when not necessary

internal/bgp/frr/frr.go, internal/bgp/frr/frr_test.go, internal/k8s/controllers/config_controller.go, internal/k8s/controllers/config_conversion.go, internal/k8s/controllers/config_conversion_test.go, internal/k8s/controllers/pool_controller.go
Backport of https://github.com/openshift/metallb/pull/132
=> OCPBUGS-15874: make the configuration stable

e2etest/bgptests/infra_setup.go, e2etest/e2etest_suite_test.go, openshift-ci/run_e2e.sh, tasks.py
Extending CI to test both ibgp and ebgp (only single hop)
=> CI: run both ebgp and ibgp tests

.snyk
Skipping:
- the vendor folder
- any test file
- all the e2etest files
Took inspiration from https://github.com/openshift/oc/blob/master/.snyk
=> Add a .snyk file with the files to skip

openshift-ci/deploy_metallb.sh, openshift-ci/run_e2e.sh
By setting an env variable in the job definition, we are able to choose which bgp backend to use.
=> Openshift CI: allow deploying and testing frr-k8s mode

e2etest/bgptests/bgp.go, e2etest/pkg/frr/bgp.go, e2etest/pkg/frr/parse.go, e2etest/pkg/frr/parse_test.go, e2etest/pkg/frr/validation.go, internal/bgp/frr/templates/neighborsession.tmpl, internal/bgp/frr/testdata/TestBFDWithSession.golden
Backport the fix and the test.
=> OCPBUGS-37293: Fix session flapping when adding a new service

openshift-ci/deploy_metallb.sh
=> Openshift CI: fix oc exec

e2etest/l2tests/l2.go, e2etest/pkg/config/validate.go, internal/allocator/allocator.go, internal/allocator/allocator_test.go, internal/allocator/stats.go, website/content/release-notes/_index.md
Adding metrics for ipfamily address usage
=> OCPBUGS-44729: Metrics: add ipv4/6 addresses_in_use_total and addresses_total

internal/bgp/frrk8s/frrk8s.go, internal/bgp/frrk8s/frrk8s_test.go, internal/bgp/frrk8s/testdata/TestTwoAdvertisementsWithSamePrefix.golden, internal/config/config.go
=> Syncmetallb21112024

openshift-ci/common.sh, openshift-ci/deploy_frr_k8s_from_cno.sh, openshift-ci/deploy_metallb.sh
Adding a script to bypass the deployment via metallb
=> Openshift CI: add a release frrk8s from CNO script 

internal/k8s/webhooks/webhookv1beta1/bfdprofile_webhook.go, internal/k8s/webhooks/webhookv1beta1/bgpadvertisement_webhook.go, internal/k8s/webhooks/webhookv1beta1/community_webhook.go, internal/k8s/webhooks/webhookv1beta1/ipaddresspool_webhook.go, internal/k8s/webhooks/webhookv1beta1/l2advertisement_webhook.go, internal/k8s/webhooks/webhookv1beta2/bgppeer_webhook.go
=> OCPBUGS-43580: fix Community update

controller/main.go, e2etest/bgptests/bgp.go, e2etest/l2tests/assignment.go, e2etest/pkg/service/create.go, internal/allocator/allocator.go, internal/config/validation.go, internal/config/validation_test.go
=> Syncmetallb 13102025

internal/k8s/epslices/endpoint_slices.go, internal/k8s/epslices/endpoint_slices_test.go, speaker/bgp_controller.go, speaker/bgp_controller_test.go, speaker/layer2_controller.go, speaker/layer2_controller_test.go
Backporting the epslices ready condition fixes.
=> OCPBUGS-51177: Fix the handling of readyness conditions of endpointslices
